### PR TITLE
185 adding qrcodemonkey

### PR DESCRIPTION
**Pull request by Rico-Smit**
I have added the QRcode monkey tool and updated the Pngegg tools logo.

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey @Rico-Smit, thank you for your contribution. There is currently a conflict with the `tools.json` file. Let me know if you need any assistance in resolving the conflict. Thanks!

**Comment by schalkneethling** [comment]
> Hey @Rico-Smit, thank you for your contribution. There is currently a conflict with the `tools.json` file. Let me know if you need any assistance in resolving the conflict. Thanks!

Heya! I made a video of how you would go about fixing something like this and used your pull request as a demo :) Hope that is OK with you. :+1:

**Review by schalkneethling — APPROVED** [review]
Thank you for your contribution! 🎉

**Comment by Rico-Smit** [comment]
> > Hey @Rico-Smit, thank you for your contribution. There is currently a conflict with the `tools.json` file. Let me know if you need any assistance in resolving the conflict. Thanks!
> 
> Heya! I made a video of how you would go about fixing something like this and used your pull request as a demo :) Hope that is OK with you. :+1:

Yeah, no problem at all. Please post the link in our community discord 😁

**Pull request merged**
