### PR TITLE
Add JSON Diff and ModHeader

### PR DESCRIPTION
**Pull request by malufell**
Add JSON Diff and ModHeader tools :)

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey @malufell, thank you for your contribution! There is currently a conflict with the `src/data/tools.json` file. Let me know if you need help resolving the conflict. :+1:

**Comment by malufell** [comment]
Hi @schalkneethling , I'm newbie to open source contribution, first hacktoberfest. I made some mistakes in resolving the conflict :fearful:, but now everything seems to be ok. if there are improvements let me know, please!

**Comment by schalkneethling** [comment]
> Hi @schalkneethling , I'm newbie to open source contribution, first hacktoberfest. I made some mistakes in resolving the conflict 😨, but now everything seems to be ok. if there are improvements let me know, please!

No worries, you did a great job. Congratulations on getting started in open-source. 🎉

**Review by schalkneethling — APPROVED** [review]
Thank you for your contribution, @malufell 🎉 🎃

**Pull request merged**
